// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"database/sql"
	"time"
)

type Event struct {
	EventID      uint32
	Name         string
	Description  string
	CreationDate sql.NullTime
}

type Photo struct {
	PhotoID      uint32
	PathToPhoto  string
	CreationDate sql.NullTime
	EventID      uint32
}

type RecognizedUser struct {
	RecognizedUserID uint32
	UserID           uint32
	PhotoID          uint32
}

type Session struct {
	SessionID    uint32
	UserID       uint32
	CreationDate time.Time
	SessionToken string
	UserAgent    string
	IpAddress    string
}

type User struct {
	UserID           uint32
	SignupDate       time.Time
	LastSigninDate   sql.NullTime
	SigninLocked     bool
	SigninLockedDate sql.NullTime
	IsAdmin          bool
	Email            string
	FullName         string
	BusinessCategory string
	DepartmentNumber string
}

type UserFolder struct {
	UserFolderID   uint32
	IsSubFolder    sql.NullBool
	Name           string
	Description    string
	CreationDate   sql.NullTime
	UserID         uint32
	ParentFolderID sql.NullInt32
}
