linters:
  disable-all: true
  enable:
    # - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - errname
    - gofmt
    - gosec
    - misspell
