server:
  port: 3000
  read_timeout: 6s
  write_timeout: 12s
  request_context_timeout: 12s
  idle_timeout: 30s
  max_header_bytes: 4096
  max_body_size: 1024

security:
  csrf_token:
    secret: 1c82f8e4a199bea6b6c92dbc99e30b7d5f7b09ce0df7183e40e4a6bd19dbdbc9
    field_name: csrf_token
    header_name: X-CSRF-Token
    cookie_name: csrf_token
    cookie_max_age: 0s
    cookie_secure: true
    cookie_http_only: true
    cookie_same_site: strict
