name: automatic release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build artifacts
        run: |
          mkdir -p artifacts
          GOOS=linux GOARCH=amd64 go build ./cmd/photos_server/launch_server.go -o artifacts/photos-server-linux-amd64
          GOOS=darwin GOARCH=amd64 go build ./cmd/photos_server/launch_server.go -o artifacts/photos-server-darwin-amd64
      - name: Generate changelog
        run: |
          git log $(git tag | tail -n 2 | head -n 1)..$(git tag | tail -n 1) --pretty=format:"%h - %an: %s" > CHANGELOG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/photos-linux-amd64
            artifacts/photos-darwin-amd64
            artifacts/photos-windows-amd64.exe
          body_path: CHANGELOG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


