name: automatic release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build artifacts
        run: |
          mkdir -p artifacts
          GOOS=linux GOARCH=amd64 go build -o artifacts/photos-server-linux-amd64 ./cmd/photos_server/launch_server.go
          GOOS=darwin GOARCH=amd64 go build -o artifacts/photos-server-darwin-amd64 ./cmd/photos_server/launch_server.go
      - name: Generate changelog
        run: |
          git log --pretty=format:"%h - %an: %s" "$(git tag | tail -n 2 | head -n 1)..$(git tag | tail -n 1)" > CHANGELOG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/photos-server-linux-amd64
            artifacts/photos-server-darwin-amd64
          body_path: CHANGELOG
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}


