name: ci
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: ['1.23.4', '1.22.10', '1.24.rc1']
    name: Testing with go version ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test -cover ./...
